FROM docker.io/kibana:latest
# https://github.com/docker-library/kibana/tree/013505006cf267437f19ebf7ab5f022aebdb5da8
# https://github.com/docker-library/kibana/blob/013505006cf267437f19ebf7ab5f022aebdb5da8/4.5/Dockerfile
Run kibana plugin --install elastic/sense